[WIP] Bsp 172 create item service
jwa-lab/item-service pull request #1
Opened 2021-09-07 04:32 UTC by podefr

2021-09-07 09:49 UTC, tkjwa reviewed
Great job, I really like the implementation and its simplicity. The abstractions around nats messages are also a good thing.
For me the main points to discuss are config management (Config.ts) and lifecycle hooks

2021-09-07 09:49 UTC, tkjwa commented on src/common/logger/WinstonLogger.ts
> +export function makeWinstonLogger(config: WinstonLoggerConfig): WinstonLogger {
I think it make sense to have a factory here as the setup of the logger is not trivial, but it should live on its own

2021-09-07 09:49 UTC, tkjwa commented on src/di.json
> +}
The config of the "common" services should not live in src, but with some kind of framework package, otherwise we will need to copy it in every new service.
Also imho, json is one of the worst format for config, mainly because you cannot add any comments. I find yaml much more dev friendly (but then we need a way to have it copied in the dist folder) or js (which looks almost like json but you have a minimum flexibility in it)

2021-09-07 09:49 UTC, tkjwa commented on src/common/NatsRunner/NatsRunner.ts
> +        loader.load(`${ this.cwd }/di.json`);
Here we should also load a config file with the "framework services" (logger, db, nats, ...) so that the developer doesn't have to re-configure those services himself

2021-09-07 09:49 UTC, tkjwa commented on src/common/logger/Logger.ts
> +export default abstract class Logger {
I know you juste copied those files, but in the end I don't really see the point of this abstract class as it's only used once

2021-09-07 09:49 UTC, tkjwa commented on src/index.ts
> +    }
See comment in the runner. If we "externalize" those methods then we can endup with something as simple as 
`const runner = new NatsRunner(__dirname); runner.start();`

2021-09-07 09:49 UTC, tkjwa commented on src/natsHandlers/createItem/CreateItem.ts
> +    constructor(item: Item) {
Doesn't make any sense to me: if you need an item to create an item then you're in a "chicken and egg" kind of situation ^^ Probably a js niceness i don't get :p

2021-09-07 09:49 UTC, tkjwa commented on src/natsHandlers/createItem/CreateItem.ts
> +import { JSONCodec, NatsConnection, SubscriptionOptions } from "nats";
Too much things in this file imo

2021-09-07 09:49 UTC, tkjwa commented on src/natsHandlers/createItem/CreateItem.ts
> +    verb = AIRLOCK_VERBS.POST;
should be const or readonly

2021-09-07 09:49 UTC, tkjwa commented on src/natsHandlers/createItem/CreateItem.ts
> +    constructor(config: Config, logger: Logger, natsConnection: NatsConnection) {
Only the service name is used so we should inject it directly

2021-09-07 09:49 UTC, tkjwa commented on src/natsHandlers/createItem/CreateItem.ts
> +    constructor(config: Config, logger: Logger) {
remove config if not used

2021-09-07 09:49 UTC, tkjwa commented on src/natsHandlers/createItem/CreateItem.ts
> +       const item = new Item(msg.body);
I don't really see the point of that Item object. In the airlock handler you could `.encode(msg.body)` and there is no reference to it in the private handler

2021-09-07 09:49 UTC, tkjwa commented on src/di.json
> +        "logger": {
rename to winston_logger and create logger as an alias pointing to winston_logger. This way we can benefit fully from the flexibility offered by the Logger interface
interface = alias, implementation = service

2021-09-10 04:48 UTC, podefr commented on src/common/NatsRunner/Handlers.ts
> +export abstract class AirlockHandler extends Handler {
agreed!

2021-09-10 04:49 UTC, podefr commented on src/common/NatsRunner/Handlers.ts
> +    abstract subject: string;
yep, will fix

2021-09-10 04:50 UTC, podefr commented on src/common/NatsRunner/NatsRunner.ts
> +                message.respond(this.jsonCodec.encode(response));
yeah actually it can, it will be serialized as "null" which can be deserialized to the `null` value so it's valid json

2021-09-10 04:51 UTC, podefr commented on src/natsHandlers/createItem/CreateItem.ts
> +import { JSONCodec, NatsConnection, SubscriptionOptions } from "nats";
split

2021-09-10 04:56 UTC, podefr commented on src/natsHandlers/getItem/GetItem.ts
> +        const item_id = Number(msg.subject.split(".")[2]);
I'm thinking about adding a `msg.arguments` that has an array of arguments. Basically for each `.` in the subject, the arguments array has the actual value, so I don't need to do the split every time, I could just do `item_id = msg.arguments[0]`

2021-09-13 09:46 UTC, tkjwa reviewed
There are a few details I'd like to discuss but I think we're getting close to a first release

2021-09-13 09:46 UTC, tkjwa commented on src/natsHandlers/getItem/GetItem.ts
> +        private SERVICE_NAME: string,
We should think on how to improve this so that we don't need to pass the service name in every handlers

2021-09-13 09:46 UTC, tkjwa commented on .prettierignore
> +coverage
missing new line

2021-09-13 09:46 UTC, tkjwa commented on package.json
> +        "@elastic/elasticsearch": "^7.14.0",
can be removed

2021-09-13 09:46 UTC, tkjwa commented on package.json
> +        "awilix": "^5.0.1",
can be removed

2021-09-13 22:28 UTC, podefr commented on knexfile.js
> +        database: process.env.PGSQL_DATABASE
yes it's exclusively used by knex cli when doing `knex migration:run` etc. The knex client in our code uses the config config.ts

2021-09-13 22:28 UTC, podefr commented on package.json
> +        "@elastic/elasticsearch": "^7.14.0",
good catch

2021-09-13 22:34 UTC, podefr commented on src/common/NatsRunner/Handlers.ts
> +    serviceScopedSubject = true;
I agree. Actually I think the issue is that the subjects are prefixed by the service name but shouldn't, it was a quick and dirty solution to distinguish between private handlers from `item-store` and `tokenization-service`.
Let's keep that for now and see if we can eventually remove the scoping of the subjects altogether. It shouldn't have any impact on the handlers, it only changes the logic in the NatsRunner

2021-09-13 22:37 UTC, podefr commented on src/common/NatsRunner/NatsRunner.ts
> +        const loader = new JsonFileLoader(this.container);
I'll go with js then :) I think it's sad to have to use additional tools to manipulate yaml when JSON is native to the language we use, but I don't mind executing js instead of writing a json file.

2021-09-13 22:42 UTC, podefr commented on src/common/logger/Logger.ts
> +    warn(message: string): void;
yes it's a requirement from `node-dependency-injection`: https://github.com/zazoomauro/node-dependency-injection/wiki/Logging

2021-09-14 01:08 UTC, podefr commented on src/common/openApi/openApi.ts
> +export class GetDocsHandler extends PrivateHandler {
no it's actually a private handler. The Airlock handler is in Airlock, and Airlock does a scatter/gather on all the service's private `docs` handlers

2021-09-14 01:10 UTC, podefr commented on src/natsHandlers/getItem/GetItem.ts
> +        const item_id = Number(msg.subject.split(".")[2]);
agreed but out of the scope for this PR.
We'd need to have some kind of templating logic to parse a string such as `item/${item_id}` and turn it into `msg.args.item_id`. This can be added at a later time without making this parsing logic obsolete

2021-09-14 01:14 UTC, podefr commented on src/natsHandlers/getItem/GetItem.ts
> +        const item_id = Number(msg.subject.split(".")[2]);
added to our jira board: https://jwalab.atlassian.net/secure/RapidBoard.jspa?rapidView=7&selectedIssue=BSP-177

2021-09-14 01:14 UTC, podefr commented on src/natsHandlers/getItem/GetItem.ts
> +        private SERVICE_NAME: string,
added to our jira board: https://jwalab.atlassian.net/secure/RapidBoard.jspa?rapidView=7&selectedIssue=BSP-177

2021-09-14 01:25 UTC, podefr commented on src/services/pgSql/pgSqlFactory.ts
> +export type PgSQL = Knex;
remove all references to PgSQL and using knex instead

2021-09-14 01:39 UTC, podefr commented on src/common/openApi/openApi.json
> +        "openApiDocs": {
I can't seem to find a nice way to load a json file using `node-dependency-injection` so I had to improvise. let me know if you find something. See my comment below on using a factory for loading the docs

2021-09-14 01:40 UTC, podefr commented on src/common/openApi/openApi.ts
> +export function makeOpenApiDocs(cwd: string, logger: Logger): Promise<void> {
fixed the return type 👍

2021-09-14 01:58 UTC, podefr commented on src/common/NatsRunner/NatsRunner.ts
> +        if (handler.serviceScopedSubject) {
it's marked as readonly in the class that defines it, should be ok?

2021-09-14 02:00 UTC, podefr commented on src/common/NatsRunner/Handlers.ts
> +    abstract verb: AIRLOCK_VERBS;
marked as readonly so it becomes readonly once it's defined in the subtype's constructor

2021-09-14 08:29 UTC, tkjwa requested changes
Great Job, thank you for the lasts updates and creating the jira tickets ;)
My only concern before merging is about the items names length which should be addressed to avoid having our service crash in case a user submits an invalid name. (see comment in the create table script)

2021-09-14 08:29 UTC, tkjwa commented on seeds/create_items_table.js
> +                table.string("name", 100).notNullable();
I think this is the last point that needs to be addressed, we should either change the column type to `.text` if we want to remove the limit, or update the validation if we want to keep the limit

2021-09-14 08:29 UTC, tkjwa commented on src/di.ts
> +        "itemRepository": {
Here you can use the same construct as with the logger: rename `itemRepository` to `knexItemRepository` and create a new `itemRepository` as an alias pointing to `knexItemRepository` so that you get "abstraction at the container level"

2021-09-14 08:37 UTC, tkjwa commented on src/common/openApi/openApi.json
> +        "openApiDocs": {
That works for me. If we want to load the content of a json file in the container, we should use a parameter, as it just a value, not a service. We will see if we need it somewhere else we can extract the loading outside of the handler

2021-09-15 01:43 UTC, podefr commented on tests/createItemAirlock.test.ts
> +        };
yes, those are now unit tests as opposed to integration tests.
our previous tests were only testing the private handlers but we're not able to fully test the private and public handlers. They're still only unit tests though, so we should discuss having maybe another test suite that would still run nats but focus on integration (as opposed to running all permutations of a payload's validation, we'd just verify that the endpoint returns an error with an invalid payload to ensure that the validation kicks in)

2021-09-15 01:44 UTC, podefr commented on tests/createItemAirlock.test.ts
> +            expect(natsConnection.request.mock.calls[0][0]).toBe(
sure, it's a pretty standard patter for unit testing using mocks/spies

2021-09-15 01:44 UTC, podefr commented on src/common/openApi/openApi.ts
> +            this.logger.warning("Unable to load openapi docs.");
I think it's acceptable. I worry that if we make too many things mandatory just to get the NatsRunner to start it will introduce too much friction. I'm fine with having a service with a couple handlers without docs at first. What do you think?

2021-09-15 01:45 UTC, podefr commented on seeds/create_items_table.js
> +                table.string("name", 100).notNullable();
sure, I'll update the validation, that makes sense

2021-09-15 02:11 UTC, podefr commented on src/common/logger/Logger.ts
> +    warn(message: string): void;
actually I removed the warn method from WinstonLogger and the Logger interface and I'm just creating the alias at the time I configure the container with the logger.

2021-09-15 07:36 UTC, tkjwa approved these changes
Good to go ! great job

2021-09-15 07:36 UTC, tkjwa commented on src/common/NatsRunner/NatsRunner.ts
> +        this.container.logger = { warn: (msg) => this.logger.warning(msg) };
I think this one is a nice usage of the flexibility of JS ! 👍

2021-09-15 07:36 UTC, tkjwa commented on src/common/openApi/openApi.ts
> +            this.logger.warning("Unable to load openapi docs.");
ok for me

2021-09-15 13:08 UTC, merged