[WIP] BSP-36: Add Tezos Work Queue
jwa-lab/item-service pull request #4
Opened 2021-09-20 02:28 UTC by podefr

- Add Tokenization Service to tokenize items into Tezos
- Add Work Queue to asynchronously process Tezos operations
- Switch to npm workspace repository

2021-09-20 08:33 UTC, 0x103 requested changes

2021-09-20 08:33 UTC, 0x103 commented on README.md
> +Start by creating a `.env` file in this project's top level folderwith the following configuration:
If I create the `.env` file at the project's top level, the command `npm run seed-db -w item-service` doesn't work and throw the following error:
`seed: password authentication failed for user "Admin"`
I think that the environment variables are not loaded. 
If I move the `.env` in the `item-service` package, the seed command works.

2021-09-20 08:33 UTC, 0x103 commented on README.md
> +npm run deploy-warehouse -w item-service
Same here, If the `.env` file is at the root level, the following error occur:
`
BSP-36-add-tezos-work-queue\item-service\node_modules\@taquito\signer\dist\taquito-signer.umd.js:386
            var encrypted = key.substring(2, 3) === 'e';
                                ^
TypeError: Cannot read property 'substring' of undefined
`

2021-09-20 08:33 UTC, 0x103 commented on README.md
> +npm run dev -w item-service
Same problem.

I Also get this error : 

 >> jetstream functionality in nats.js is preview functionality 
[1] debug:   Successfully loaded Warehouse contract at KT1CwzueGxSjihhWWCWKR2TbcuyESDpUHTtw
[1] NatsError: TIMEOUT
[1]     at Function.errorForCode (\dev\PRs\BSP-36-add-tezos-work-queue\item-service\node_modules\nats\lib\nats-base-client\error.js:98:16)
[1]     at Timeout.<anonymous> (\dev\PRs\BSP-36-add-tezos-work-queue\item-service\node_modules\nats\lib\nats-base-client\util.js:82:38)
[1]     at listOnTimeout (internal/timers.js:554:17)
[1]     at processTimers (internal/timers.js:497:7) {
[1]   code: 'TIMEOUT',
[1]   chainedError: undefined
[1] }

2021-09-20 08:33 UTC, 0x103 commented on README.md
> +npm run dev -w tezos-work-queue
Same problem.

And this one:

> [1]  >> jetstream functionality in nats.js is preview functionality 
[1] NatsError: TIMEOUT
[1]     at Function.errorForCode (\dev\PRs\BSP-36-add-tezos-work-queue\item-service\node_modules\nats\lib\nats-base-client\error.js:98:16)
[1]     at Timeout.<anonymous> (\dev\PRs\BSP-36-add-tezos-work-queue\item-service\node_modules\nats\lib\nats-base-client\util.js:82:38)   
[1]     at listOnTimeout (internal/timers.js:554:17)
[1]     at processTimers (internal/timers.js:497:7) {
[1]   code: 'TIMEOUT',
[1]   chainedError: undefined
[1] }

2021-09-20 10:41 UTC, tkjwa approved these changes
Very nice ! lots of great additions here.

I am wondering if Tezos related code should live in the item service or not, I'll explain myself when we'll review it togehter.

Also we should merge it asap and continue improvements in other PR as it is blocking for Julien to move forward on the handlers.

Quick question about the change of folder structure: will each folder in `packages` live in its own repo ?

IMO the negative point is the use of `Pick<item_id`  construct which make the code less explicit

2021-09-20 10:41 UTC, tkjwa commented on packages/item-service/src/natsHandlers/createItem/CreateItem.ts
>  export class CreateItemAirlockHandler extends AirlockHandler {
We should consider adding common dependencies (logger, messagebus, ...) to the handlers to improve DX, setter injection could be acceptable for this use case

2021-09-20 10:41 UTC, tkjwa commented on packages/item-service/src/services/tokenization/TokenizationService.ts
> +    createItem(itemId: Pick<Item, "item_id">): void;
should we use a more blockchain-oriented name ? mintItem ?

2021-09-20 10:41 UTC, tkjwa commented on packages/item-service/src/services/tokenization/TokenizationService.ts
> +    ITEM_CREATED = "ItemCreated"
IMO this event should not live in a tokenisation context/namespace, it will still be relevant event if we'd stop writing items to blockchain

2021-09-20 10:41 UTC, tkjwa commented on packages/item-service/tests/utils/mockMessageBus.ts
> +export default {
Could we create mocks in the test code with something like `const bus = jest.mock(MessageBus)` instead ?

2021-09-20 10:41 UTC, tkjwa commented on packages/tezos-work-queue/src/TezosWorkQueuePlugin.ts
> +export class TezosWorkQueuePlugin implements RunnerPlugin {
Do you think we could make a new type of handler (WorkerHandler) instead of a plugin and keep a simple interface for message handling ?

2021-09-20 10:41 UTC, tkjwa commented on packages/tezos-work-queue/src/TezosWorkQueuePlugin.ts
> +                );
what line length is the max ? could be reduced to 3 lines at least

2021-09-20 12:55 UTC, podefr commented on README.md
> +Start by creating a `.env` file in this project's top level folderwith the following configuration:
can you check if you have an alias of `.env` in the `item-service` folder? the alias should be checked-in

2021-09-21 02:37 UTC, podefr commented on README.md
> +Start by creating a `.env` file in this project's top level folderwith the following configuration:
should be fixed with the .env aliases added to git

2021-09-21 02:38 UTC, podefr commented on packages/common/src/MessageBus/EventEmitterMessageBus.ts
> +    return () => this.eventEmitter.off(eventName, callback);
it's not currently used but I'm establishing now that to unsubscribe we'd just call the function returned by subscribe :) It's a pattern that I like, I think it's better than calling a `.off` method and find the eventName AND a reference to the callback again. Most pub/sub libs use this pattern now, as opposed to the one used by eventEmitter which I don't see very often anymore

2021-09-21 02:50 UTC, podefr commented on packages/common/src/MessageBus/MessageBus.ts
> +  publish(eventName: string, ...params: unknown[]): void;
so this got tricky. I can't infer the name from the event class, because when the class is initialized (new Class) the `.name` property can't be accessed anymore, so when I publish the event I can't get the `name` and don't know the subject name.
I had to create an Event and ensure (using TS) that the property `name` is present. Now the issue is that `name` is only there when the object is newed up, so I can't pass the class as a parameter and extract it's name when I subscribe. LOL
I thought about using a static property instead, but can't use a static property called "name" because it conflicts with...  the classes's name before it's newed up. I tried using another property name and then realized that I can't create an interface that requires a member when that member is static.

So long story short, all I could do was to ensure that the event passed to pub/sub has a property "name", set when the class is newed up, and when I subscribe to an event I use TS to verify that the event's name matches the event type. It requires passing a string to subscribe as a first argument but at least if there's a typo in the string we'll get an error :)

2021-09-21 02:58 UTC, podefr commented on packages/item-service/src/natsHandlers/createItem/CreateItem.ts
>  export class CreateItemAirlockHandler extends AirlockHandler {
let's make a not to chat about it and address in next PR

2021-09-21 02:58 UTC, podefr commented on packages/item-service/src/repositories/ItemRepository.ts
> +    getItem(item_id: Pick<Item, "item_id">): Promise<Item>;
removed

2021-09-21 02:59 UTC, podefr commented on packages/item-service/src/services/Tezos/TezosTokenizationService.ts
> +        // we should add a compilerPass with an async tag to work around this and maybe raise an issue with the library.
yes I agree, would like to tackle this in the next PR

2021-09-21 02:59 UTC, podefr commented on packages/item-service/src/services/tokenization/TokenizationService.ts
> +    ITEM_CREATED = "ItemCreated"
fixed

2021-09-21 02:59 UTC, podefr commented on packages/item-service/src/services/tokenization/TokenizationService.ts
> +    createItem(itemId: Pick<Item, "item_id">): void;
currently it's a 1:1 correspondance with the contract method, it's kind of useful :)

2021-09-21 03:01 UTC, podefr commented on packages/item-service/tezos/deploy.js
> +        const operation = await tezosClient.contract.originate({
unfortunatly the `seeds` folder is a convention for knex, I worry about putting tezos scripts in there because of conflicts.
I'm sure when we have to use those scripts upon deploying a new env we can find a better place for them

2021-09-21 03:02 UTC, podefr commented on packages/tezos-work-queue/src/TezosClient.ts
> +export function makeTezosClient(
agreed, I'd like to do that in another PR or when we extract that to the common repository

2021-09-21 03:02 UTC, podefr commented on packages/tezos-work-queue/src/TezosWorkQueuePlugin.ts
> +export class TezosWorkQueuePlugin implements RunnerPlugin {
yes, a Nats jetstream handler would make a lot of sense, thanks for the suggestion. Will fix it in a next PR so we can merge this one in and make progress on the other NATS handlers

2021-09-21 03:03 UTC, podefr commented on packages/tezos-work-queue/src/TezosWorkQueuePlugin.ts
> +                );
ah, I didn't do this it's set by default by prettier (it's very opinionated so we don't have to be)

2021-09-21 03:06 UTC, podefr commented on packages/item-service/src/services/Tezos/TezosPlugin.ts
> +            "ItemCreatedEvent",
no way to read this string from the constructor (the class). I pass a string instead that matches the event name, but this works since the type checking will statically verify that the 2 are indeed matching. See my comment in discussions as to why I had to resort to this solution

2021-09-21 08:08 UTC, tkjwa commented on packages/common/src/MessageBus/MessageBus.ts
> +  publish(eventName: string, ...params: unknown[]): void;
😲 sorry i brought that up lol
As we need to work with strings anyway we could still use an enum to reference all those events name
`class ItemCreated { name = ItemEvents.ItemCreated ....` `subscribe(ItemEvents.ItemCreated, () => ...`

2021-09-21 08:15 UTC, tkjwa approved these changes
good to go ! thanks for the updated. I left some conversations unresolved for later reference (the "in the next PR" ones)

2021-09-21 08:17 UTC, 0x103 approved these changes

2021-09-21 08:21 UTC, merged