BSP-112: Studio ID, User ID, Token management.
jwa-lab/item-service pull request #5
Opened 2021-09-21 10:01 UTC by 0x103

feat(common/src/utils/tokenParser.ts): Parsing utils for airlock jwt.
feat(item-service/tests/getItemPrivate.test.ts): Tests for the GetItem private handler.
--
fix(package.json): Minilab version bump to 0.15.
fix(common/package.json): jwt-decode added.
fix(common/src/NatsRunner/Messages.ts): natsHeadersToObject function updated.
fix(common/src/NatsRunner/NatsRunner.ts): utils index export.
fix(item-service/seeds/create_items_table.js): studio id & user id added.
fix(item-service/src/entities/item.ts): studio_id & user_id added.
fix(item-service/src/natsHandlers/createItem/CreateItem.ts): Token management added.
fix(item-service/src/natsHandlers/getItem/GetItem.ts): Token management added.
fix(openapi-docs.json): Optional user_id added.
fix(item-service/tests/createItemAirlock.test.ts): ids added.

2021-09-21 13:14 UTC, tkjwa commented on packages/item-service/tests/getItemPrivate.test.ts
> +                "name": "laboris ut eu",
Le latin c'est has-been ! https://schnaps.it/

2021-09-21 13:14 UTC, tkjwa commented on packages/item-service/tests/getItemPrivate.test.ts
> +        });
If don't think this assertion is usefull because it ties your test to the implementation even more, as we have a nice i/o use case we should stick to it

2021-09-21 13:14 UTC, tkjwa commented on packages/item-service/tests/getItemPrivate.test.ts
> +            });
can it be moved to the repo definition: `getItem: jest.fn().mockReturnValue(...)` so we have a nice default for all tests

2021-09-21 13:14 UTC, tkjwa commented on packages/item-service/tests/createItemAirlock.test.ts
> +            ).rejects.toThrow("\"name\" is required");
Did prettier did that ? 🤣

2021-09-21 13:15 UTC, 0x103 commented on packages/item-service/tests/createItemAirlock.test.ts
> +            ).rejects.toThrow("\"name\" is required");
My Webstorm yes ahah.

2021-09-21 13:15 UTC, 0x103 commented on packages/item-service/tests/getItemPrivate.test.ts
> +            });
Yes, of course.

2021-09-21 13:25 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItem/GetItem.ts
> +            }
I see, thank you, I keep that in mind.

2021-09-21 13:43 UTC, podefr commented on packages/item-service/src/entities/item.ts
> +    studio_id: Joi.string().required(),
the schema is validating the body of a POST request via Airlock, I don't think the item_id is provided via the body, it's read from the logged in user, right?

2021-09-21 13:43 UTC, tkjwa approved these changes

2021-09-21 13:51 UTC, podefr commented on packages/common/src/utils/tokenParser.ts
> +    parsedJwt["is_studio"] = String(decoded?.studio) || "";
should we parse that to a boolean? the risk is that later on in the code we may think that testing (headers?.is_studio) is enough to test for truthiness where (headers?.is_studio) is truthy even if the value is `"false"`

2021-09-21 13:52 UTC, podefr commented on packages/common/src/utils/tokenParser.ts
> +export function isStudio(headers: Record<string, unknown> | undefined): boolean {
I'd suggest always passing `headers` even if it's an empty object, instead of having checks to see if headers is defined or not.

2021-09-21 13:56 UTC, 0x103 commented on packages/common/src/utils/tokenParser.ts
> +    parsedJwt["is_studio"] = String(decoded?.studio) || "";
That's true ! I'll fix this for this case.

2021-09-21 14:28 UTC, podefr commented on packages/common/src/utils/tokenParser.ts
> +export function isStudio(headers: Record<string, unknown> | undefined): boolean {
we should probably fix this then and make headers always set, @tkjwa what do you think?

2021-09-22 00:20 UTC, podefr commented on packages/common/src/NatsRunner/Messages.ts
> +  let obj = Object.create(null);
the goal here was to create a headers object without prototype (Object.create(null)) and add the headers to it.
Now if we override this object on line 55 with a new object literal, this becomes moot.
Actually, sometimes it will return an object with a prototype, sometimes without a prototype.

```
hop = Object.create(null)
>> {}

lol = {}
>> {}

Object.getPrototypeOf(hop)
>> null

Object.getPrototypeOf(lol)
>> {constructor: ƒ, __defineGetter__: ƒ, __defineSetter__: ƒ, hasOwnProperty: ƒ, __lookupGetter__: ƒ, …}
```

Let's do `Object.assign(obj, parseJwtToNats(obj.authorization))` instead and line 53, and make `obj` a const again

2021-09-22 00:29 UTC, podefr commented on packages/item-service/src/natsHandlers/createItem/CreateItem.ts
> +            ...(msg.body as { [key: string]: unknown }),
I think you can do something like `Partial<Item>` instead of defining a type on fly here

2021-09-22 00:30 UTC, podefr commented on packages/item-service/src/natsHandlers/createItem/CreateItem.ts
> +            studio_id: msg.headers?.studio_id
I don't think you need elvis here (?) since we're always returning headers `{}` now

2021-09-22 00:34 UTC, podefr commented on packages/item-service/src/entities/item.ts
> +    studio_id: Joi.string().required(),
yes, let's remove `item_id` since it's not used (note that it's not marked as required, that's why creating an item without item_id worked, but this check is actually never executed)
The goal of the validator is not to validate the Item itself but the user input I think, and the user input won't have studio_id as you mentioned. I would suggest changing our logic a bit in the Public handler and doing something like:

1. remove item_id and studio_id from the validator
2. as soon as we enter the public handler, let's call itemValidator.validate(msg.body)
3. verify the JWT is from a studio
4. call the private handler with a new item with the studio id. 

We're basically moving the validation call before we create the Item where studio_id is required

2021-09-22 00:36 UTC, podefr commented on packages/item-service/src/natsHandlers/getItem/GetItem.ts
> +            throw new Error("Invalid token type, a studio token is required.");
do we need to be a studio to retrieve an item?

2021-09-22 00:38 UTC, podefr commented on packages/item-service/src/openapi-docs.json
> +                                    "studio_id": {
given that studio ID doesn't come from the POST request, it shouldn't be in the schema here

2021-09-22 00:41 UTC, podefr requested changes
please see comments

2021-09-22 07:22 UTC, tkjwa commented on packages/item-service/src/entities/item.ts
> +    studio_id: Joi.string().required(),
Sounds good to me ! the validation in the public handler must be user friendly and return nice errors messages allowing the api consumer to fix his request maybe.
We still need some kind of validation on the private side

2021-09-22 07:23 UTC, tkjwa commented on packages/item-service/src/natsHandlers/getItem/GetItem.ts
> +            throw new Error("Invalid token type, a studio token is required.");
imo a player will retrieve infos about his items via `GetInstance`

2021-09-22 07:50 UTC, 0x103 commented on packages/item-service/src/openapi-docs.json
> +                                    "studio_id": {
Of course, yes.

2021-09-22 07:56 UTC, 0x103 commented on packages/item-service/src/natsHandlers/createItem/CreateItem.ts
> +            studio_id: msg.headers?.studio_id
Indeed.

2021-09-22 07:57 UTC, 0x103 commented on packages/item-service/src/natsHandlers/createItem/CreateItem.ts
> +            ...(msg.body as { [key: string]: unknown }),
I keep that in mind, thank you.

2021-09-22 08:10 UTC, 0x103 commented on packages/common/src/NatsRunner/Messages.ts
> +  let obj = Object.create(null);
Much better, yes, thank you.

2021-09-22 08:14 UTC, 0x103 commented on packages/item-service/src/entities/item.ts
> +    studio_id: Joi.string().required(),
Perfect. Should we keep the studio validation (isStudio) at the public handler level, or should we delegate this to the private handler ?

2021-09-22 08:16 UTC, 0x103 commented on packages/common/src/utils/tokenParser.ts
> +export function isStudio(headers: Record<string, unknown> | undefined): boolean {
Updated the type in `AirlockMessage` and `Message`, then updated `isStudio` parameter type.

2021-09-22 11:54 UTC, podefr commented on packages/item-service/src/natsHandlers/getItem/GetItem.ts
> +                is_studio: msg.headers?.is_studio,
elvis isn't required here anymore, let's remove the `?`

2021-09-22 11:54 UTC, podefr approved these changes

2021-09-22 12:46 UTC, merged