WIP - BSP-187: Get Items
jwa-lab/item-service pull request #6
Opened 2021-09-22 15:31 UTC by 0x103

- Get Items handler added to fetch a list of items.

2021-09-23 03:31 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +            page: parseInt(query.page),
to do type casting in JS we should use the corresponding constructor function. So to parse to a number, we should do `Number(quer.page)`

also, what do `page, perPage` represent?
if I do `page: 3` and `perPage 10`, does that mean I want items 30 to 40?

2021-09-23 03:36 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +            perPage: parseInt(query.perPage) || undefined
why defaulting to undefined here?

2021-09-23 03:37 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        if (parsedQuery.page < 1) {
this validation is already happening in `await getItemsSchema.validateAsync()`  since you put `.min(1)` in the joi schema, you should be able to remove this if block

2021-09-23 03:38 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +                is_studio: msg.headers.is_studio,
should is_studio be set here, or should it be read from the headers/jwt in the private handler?

2021-09-23 03:40 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        if (!data?.is_studio) {
we should probably fail before we make an expensive call to the DB. I'd move this check up before calling `getItems`

2021-09-23 03:41 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        if (!data?.is_studio) {
also, is_studio should come from the headers, It looks like `msg` has the headers and the JWT

2021-09-23 03:46 UTC, podefr commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +        const offset = (page - 1) * perPage;
yeah I think we're a bit too clever here, we are asking the developer to do some math to figure out start/limit and then we're "decomputing" that to go back to start/limit. Let's just ask the dev to pass in start/limit

2021-09-23 03:48 UTC, podefr commented
thanks for pushing your work in progress, it's looking good! I already noticed a few things to discuss, see my comments in line. Thanks!

2021-09-23 07:50 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +            page: parseInt(query.page),
From now on, I'll ban toString and parseInt then :)

Very well.

2021-09-23 07:54 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +            perPage: parseInt(query.perPage) || undefined
If perPage is not defined by the user, parseInt was returning NaN, which was failing the validation.

2021-09-23 08:03 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +                is_studio: msg.headers.is_studio,
As our headers are not Nats Headers anymore, we have to reconstruct another natsHeader, which will have to be re-parsed. I talked about it with @tkjwa for the `GetItem` handler and it was ok to put those variables in the payload.
Maybe we should talk about it and clarify when to create a new natsHeaders from the public handler?

2021-09-23 08:16 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        if (!data?.is_studio) {
I'll move the check up. `data` may be null if the private handler is called directly without a payload, here is the parsing from `Message`:

> this.data = String(data)
      ? JSONCodec<Record<string, unknown>>().decode(data)
      : null;

I agree to make data an empty object by default instead of being null. However, this mean that we'll not be able to directly check if the Message has some data or is empty and we will have to either check the keys length of the object or directly the key we are looking for.

2021-09-23 08:16 UTC, 0x103 commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +        const offset = (page - 1) * perPage;
Very well.

2021-09-24 03:15 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/di.ts
> +        GetItemAirlock: {
`GetItemsAirlock` and `GetItems`. The current names override the DI config for the actual `GetItem` handlers so they won't get registered

2021-09-24 03:16 UTC, podefr commented on packages/item-service/src/openapi-docs.json
> +                        "description": "End of the results",
thanks for switching to start/limit. I think limit represents the max number of results to return as opposed to something like max item_id. Should we say "Max number of results" instead?

2021-09-24 03:19 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        const parsedQuery = {
should we provide reasonable defaults here like 0 and 10?

2021-09-24 03:23 UTC, podefr commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +            "total": Number(total?.count) || -1,
in what case would count be undefined? And if there are no items, should the total be 0?

2021-09-24 03:24 UTC, podefr commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +            perPage,
given that we have removed the notion of page size, (the page size is however many results the client asked for) should we simply remove perPage?

2021-09-24 03:24 UTC, podefr commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +            result,
`results`?

2021-09-24 03:29 UTC, podefr commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        if (!data?.is_studio) {
actually let's not make data an empty object by default, you're right that given that it's a private handler `data` could be anything, undefined, a string etc. We can still remove the `?` though, we're assuming that `data` is an object anyway (`msg.data as GetItemsPrivatePayloadInterface`) and we're not optionnally chaining when invoking `this.itemRepository.getItems`

2021-09-24 03:30 UTC, podefr requested changes
looks really good thanks! 
The only issue is the di config for GetItems given that it overrides the loading of the `GetItem` handlers. 
also a few minor comments, and please remember to run `npm run prettier --ws` before your n ext push to ensure proper formatting.

thanks!

2021-09-27 08:15 UTC, 0x103 commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +            result,
I originally wrote `results`, but htough it would be better to have the same variable name everywhere (payload included).

2021-09-27 08:16 UTC, 0x103 commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +            perPage,
Yes.

2021-09-27 08:35 UTC, 0x103 commented on packages/item-service/src/repositories/KnexItemRepository.ts
> +            "total": Number(total?.count) || -1,
It was to prevent this error to arise:
`TS2532: Object is possibly 'undefined'.` as giving an Interface didn't worked.
`const total = await this.knex<CountInterface>`.
With:

> interface CountInterface {
    [k:string]: string
}

Or

> interface CountInterface {
    count: string
}
If you have any idea, I'll be glad to read it !


if there are no items the cast will work as expected and return 0, but if an error comes up, -1 will be returned.

2021-09-27 08:37 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +        const parsedQuery = {
Yes.

2021-09-27 08:53 UTC, 0x103 commented on packages/item-service/src/openapi-docs.json
> +                        "description": "End of the results",
Yep, absolutely.

2021-09-27 08:54 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/di.ts
> +        GetItemAirlock: {
Oops, yes, sorry for that, I forgot it.

2021-09-27 10:03 UTC, 0x103 commented on packages/item-service/src/natsHandlers/getItems/GetItems.ts
> +            start: Number(query?.start) || 0,
Optional chaining added because `query` has no default value.

2021-09-28 02:46 UTC, podefr approved these changes
LGTM, good job!

2021-09-28 09:27 UTC, merged